version: '3'
services:
        database:
                image: "flumecloudservices/database"
                environment:
                        - FLUME_DATABASE_ADMIN=admin
                        - FLUME_DATABASE_SECRET=this_is_a_secret_token
                ports:
                        - "5000:8080"
        file-storage:
                image: "flumecloudservices/file-storage"
                environment:
                        - FLUME_FILE_STORAGE_ADMIN=admin
                        - FLUME_FILE_STORAGE_SECRET=this_is_a_secret_token
                ports:
                        - "5001:8080"
        cache:
                image: "flumecloudservices/cache"
                environment:
                        - FLUME_CACHE_ADMIN=admin
                        - FLUME_CACHE_SECRET=this_is_a_secret_token
                ports:
                        - "5002:8080"